version: 0.2

phases:
  install:
    commands:
      - echo "Installing nvm..."
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      - [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      - echo "Installing Node.js v20.12.2..."
      - nvm install 20.12.2
      - nvm use 20.12.2
      - nvm alias default 20.12.2
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Running tests..."
      - npm test
      - echo "Building the project..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
    - 'build/**/*'
  base-directory: 'build'
  discard-paths: yes
cache:
  paths:
    - 'node_modules/**/*'
