name: frontend s3 deployment

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: download repository
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2

      - name: install dependencies
        run: npm install
  
      - name: build static file
        run: npm run build
  
      - name: deploy to s3
        env: 
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 rm -rf "./*" s3://${S3_BUCKET}
          aws s3 sync "dist/static" s3://${S3_BUCKET}
